name: u_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_swiper_view: ^1.1.8
  flutter_blue_plus: ^1.35.12
  universal_io: ^2.2.2
  flutter_libserialport: ^0.6.0
  bluetooth_low_energy: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:
  assets:
    - lib/blue/lv_img_ac.png


  uses-material-design: true

